2 actvie color support
Kully/pixel-paint pull request #14
Opened 2023-03-27 10:24 UTC by aleksi100

2023-03-28 08:44 UTC, Kully requested changes
Really good work.

There are a changes I've requested but should be good to go after that. :)

2023-03-28 08:44 UTC, Kully commented on README.md
> +| color swap       | C                   |
Nice job!

2023-03-28 08:44 UTC, Kully commented on js/script.js
> +    "1nd-Color": palette_color_array[palette_color_array.length - 1],
Small nitpick, but can you rename `1nd-Color` and `2nd-Color` to `firstColor` and `secondColor` respectively? It's best to keep the camelCase consistent in at least this STATE object.

2023-03-28 08:44 UTC, Kully commented on js/script.js
> +
Zap this blank line

2023-03-28 08:44 UTC, Kully commented on main.css
> +#active-color-preview-2 {
There is a lot of overlap between `#active-color-preview-1` and `#active-color-preview-2`.

For the sake of reducing repeated code, can you define them like this?

```css

#active-color-preview-1 #active-color-preview-1 {
...
}

/* Then you can specify the things that are different below */
#active-color-preview-1 {
...
}
#active-color-preview-2 {
...
}

2023-03-28 08:44 UTC, Kully commented on main.css
> +	width: calc(var(--palette-width)/2.4);
Where does the 2.4 come from?

2023-03-29 08:19 UTC, aleksi100 commented
Thanks for good feedback, is it now better

2023-03-29 12:49 UTC, Kully commented
> Thanks for good feedback, is it now better

Looks fantastic, thank you very much for addressing. :)

2023-03-29 12:49 UTC, Kully approved these changes

2023-03-29 12:49 UTC, merged

2023-03-29 12:50 UTC, Kully commented
Merged 🎉🎉🎉 Thank you so much for your contribution.